# Generated by Django 5.2.7 on 2026-03-04 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_remove_codigo_default_filaatendimento'),
        ('clients', '0009_client_ativo'),
        ('patients', '0005_pet_status'),
        ('scheduling', '0003_alter_appointment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='Dia da Semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='veterinario',
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('duracao_minutos', models.IntegerField(verbose_name='Duração (minutos)')),
                ('celular_cliente', models.CharField(blank=True, max_length=20, verbose_name='Celular do Cliente')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('espera', 'Espera'), ('em_atendimento', 'Em atendimento'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='agendado', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='patients.pet', verbose_name='Animal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='clients.client', verbose_name='Cliente/Responsável')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='cadastros.filaatendimento', verbose_name='Fila de Atendimento')),
                ('tipo_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='cadastros.tipoatendimento', verbose_name='Tipo de Atendimento')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_veterinario', to=settings.AUTH_USER_MODEL, verbose_name='Veterinário')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAgendaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atendimento', models.CharField(choices=[('nao_realiza', 'Não, este usuário não realiza atendimentos'), ('escala_fixa', 'Sim, este usuário realiza atendimentos e possui escala semanal fixa'), ('escala_variavel', 'Sim, este usuário realiza atendimentos e possui escala variável (Exemplo: Plantonistas)')], default='escala_fixa', max_length=20, verbose_name='Realiza Atendimentos')),
                ('permissao_agenda', models.CharField(choices=[('todas', 'Este usuário pode ver e alterar a agenda de outros usuários'), ('propria', 'Este usuário pode ver e alterar apenas a própria agenda')], default='propria', max_length=10, verbose_name='Permissão de Agenda')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horário de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_agenda', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração de Agenda do Usuário',
                'verbose_name_plural': 'Configurações de Agenda dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='FilaDiaCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_calendario', to='cadastros.filaatendimento', verbose_name='Fila de Atendimento')),
            ],
            options={
                'verbose_name': 'Fila em Dia do Calendário',
                'verbose_name_plural': 'Filas em Dias do Calendário',
                'ordering': ['data', 'fila__nome'],
            },
        ),
    ]
