# Generated by Django 5.2.7 on 2026-03-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_alter_medicalrecord_appointment'),
        ('scheduling', '0004_horariofuncionamento_remove_appointment_pet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AlterUniqueTogether(
            name='filadiacalendario',
            unique_together={('fila', 'data')},
        ),
    ]
