# Generated by Django 6.0.2 on 2026-03-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_agendamento_options_agendamento_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
    ]
