# Generated by Django 5.2.7 on 2026-03-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_agendamento_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtendimentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='Dia da Semana')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horário de Término')),
                ('trabalha', models.BooleanField(default=True, verbose_name='Trabalha neste dia')),
                ('config_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_semanais', to='scheduling.configuracaoagendausuario', verbose_name='Configuração do Usuário')),
            ],
            options={
                'verbose_name': 'Horário de Atendimento do Usuário',
                'verbose_name_plural': 'Horários de Atendimento dos Usuários',
                'ordering': ['dia_semana'],
                'unique_together': {('config_usuario', 'dia_semana')},
            },
        ),
    ]
