# Generated by Django 5.2.7 on 2026-03-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_horarioatendimentousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_hora_chegada',
            field=models.DateTimeField(blank=True, help_text='Quando o paciente chegou (status mudou para "espera")', null=True, verbose_name='Data/Hora de Chegada'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_hora_fim_atendimento',
            field=models.DateTimeField(blank=True, help_text='Quando o atendimento terminou (status mudou para "atendido")', null=True, verbose_name='Data/Hora de Fim do Atendimento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_hora_inicio_atendimento',
            field=models.DateTimeField(blank=True, help_text='Quando o atendimento começou (status mudou para "em_atendimento")', null=True, verbose_name='Data/Hora de Início do Atendimento'),
        ),
    ]
