# Generated by Django 5.2.7 on 2026-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_patologia_descricao_alter_atributoexame_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='grupo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
