# Generated by Django 5.2.7 on 2026-02-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_vacina_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='fabricante',
        ),
    ]
