# Generated by Django 5.2.7 on 2026-02-19 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_vacina_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='filaatendimento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='patologia',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='patologia',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='raca',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racas', to='cadastros.especie', verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='tipoatendimento',
            name='duracao_padrao',
            field=models.PositiveIntegerField(default=30, help_text='Duração em minutos', verbose_name='Duração Padrão (min)'),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='grupo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Grupo'),
        ),
    ]
