# Generated by Django 5.2.7 on 2026-02-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_exame_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoatendimento',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='tipoatendimento',
            name='fluxo_agenda',
            field=models.CharField(choices=[('clinico', 'Atendimento Clínico'), ('banho_tosa', 'Atendimento Banho e Tosa'), ('simplificado', 'Fluxo Simplificado')], default='clinico', max_length=20, verbose_name='Fluxo da Agenda'),
        ),
        migrations.AddField(
            model_name='tipoatendimento',
            name='frequencia_recomendada',
            field=models.CharField(choices=[('nao_recorrente', 'Não é recorrente'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='nao_recorrente', max_length=20, verbose_name='Frequência Recomendada'),
        ),
        migrations.AddField(
            model_name='tipoatendimento',
            name='mensagens_automaticas',
            field=models.BooleanField(default=False, verbose_name='Envio de Mensagens Automáticas'),
        ),
        migrations.AddField(
            model_name='tipoatendimento',
            name='modelo_atendimento',
            field=models.TextField(blank=True, null=True, verbose_name='Modelo de Atendimento'),
        ),
    ]
