# Generated by Django 5.2.7 on 2026-02-21 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_tipoatendimento_codigo_tipoatendimento_fluxo_agenda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='grupo',
        ),
        migrations.AddField(
            model_name='vacina',
            name='codigo',
            field=models.CharField(default='000', editable=False, max_length=10, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='laboratorios',
            field=models.TextField(blank=True, null=True, verbose_name='Laboratórios'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='tipo',
            field=models.CharField(choices=[('antiparasitario', 'Antiparasitário'), ('vacinas', 'Vacinas'), ('vermifugos', 'Vermífugos')], default='vacinas', max_length=50, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ProtocoloVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('aplicacao', models.CharField(choices=[('indeterminado', 'Tempo Indeterminado'), ('1', 'Apenas 1 dose'), ('2', 'Apenas 2 doses'), ('3', 'Apenas 3 doses'), ('4', 'Apenas 4 doses'), ('5', 'Apenas 5 doses'), ('6', 'Apenas 6 doses'), ('7', 'Apenas 7 doses'), ('8', 'Apenas 8 doses'), ('9', 'Apenas 9 doses'), ('10', 'Apenas 10 doses')], max_length=20, verbose_name='Aplicação')),
                ('intervalo_dias', models.IntegerField(verbose_name='Intervalo (dias)')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos_vacina', to='cadastros.especie', verbose_name='Espécie')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='cadastros.vacina', verbose_name='Vacina')),
                ('vem_apos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_posteriores', to='cadastros.protocolovacina', verbose_name='Vem após')),
            ],
            options={
                'verbose_name': 'Protocolo de Vacina',
                'verbose_name_plural': 'Protocolos de Vacinas',
                'ordering': ['nome'],
            },
        ),
    ]
