# Generated by Django 5.2.7 on 2026-02-21 02:20

from django.db import migrations


def populate_codigos(apps, schema_editor):
    """Popula os códigos das vacinas existentes de forma sequencial"""
    Vacina = apps.get_model('cadastros', 'Vacina')
    for index, vacina in enumerate(Vacina.objects.all().order_by('id'), start=1):
        vacina.codigo = str(index).zfill(3)
        vacina.save()


def reverse_populate(apps, schema_editor):
    """Função reversa - não faz nada pois é só dados"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_remove_vacina_grupo_vacina_codigo_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_codigos, reverse_populate),
    ]
