# Generated by Django 5.2.7 on 2026-02-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_populate_vacina_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='codigo',
            field=models.CharField(default='000', editable=False, max_length=10, unique=True, verbose_name='Código'),
        ),
    ]
