# Generated by Django 5.2.7 on 2026-02-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_vacina_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empreendimento', models.CharField(max_length=200, verbose_name='Nome do Empreendimento')),
                ('cnpj', models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual')),
                ('registro_crmv', models.CharField(help_text='Registro no Conselho Regional de Medicina Veterinária', max_length=50, verbose_name='Registro CRMV')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(help_text='UF - Ex: SP, RJ, MG', max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(help_text='Formato: 00000-000', max_length=9, verbose_name='CEP')),
                ('telefone_comercial', models.CharField(help_text='Formato: (00) 0000-0000', max_length=20, verbose_name='Telefone Comercial')),
                ('celular', models.CharField(help_text='Formato: (00) 00000-0000', max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('logomarca', models.ImageField(blank=True, help_text='Logo da clínica para uso em documentos', null=True, upload_to='unit_logos/', verbose_name='Logomarca')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Dados da Unidade',
                'verbose_name_plural': 'Dados da Unidade',
            },
        ),
    ]
