# Generated by Django 5.2.7 on 2026-02-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_dadosunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosunidade',
            name='registro_crmv',
            field=models.CharField(blank=True, help_text='Registro no Conselho Regional de Medicina Veterinária', max_length=50, verbose_name='Registro CRMV'),
        ),
        migrations.AlterField(
            model_name='dadosunidade',
            name='telefone_comercial',
            field=models.CharField(blank=True, help_text='Formato: (00) 0000-0000', max_length=20, verbose_name='Telefone Comercial'),
        ),
    ]
