# Generated by Django 5.2.7 on 2026-02-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_alter_dadosunidade_registro_crmv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosunidade',
            name='contatos_adicionais',
            field=models.JSONField(blank=True, default=list, help_text='Lista de contatos adicionais em formato JSON', verbose_name='Contatos Adicionais'),
        ),
    ]
