# Generated by Django 5.2.7 on 2026-02-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_dadosunidade_contatos_adicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='conteudo_apresentacao',
            field=models.TextField(blank=True, help_text='Conteúdo da seção de apresentação', verbose_name='Apresentação'),
        ),
        migrations.AddField(
            model_name='exame',
            name='conteudo_encerramento',
            field=models.TextField(blank=True, help_text='Conteúdo da seção de encerramento', verbose_name='Encerramento'),
        ),
        migrations.AddField(
            model_name='exame',
            name='modelo_cabecalho',
            field=models.IntegerField(choices=[(1, 'Logo + Básico'), (2, 'Logo + Completo'), (3, 'Apenas Logo'), (4, 'Sem Cabeçalho')], default=1, verbose_name='Modelo do Cabeçalho'),
        ),
        migrations.AddField(
            model_name='exame',
            name='modelo_info_paciente',
            field=models.IntegerField(choices=[(1, 'Animal + Responsável Resumido'), (2, 'Animal + Responsável Completo'), (3, 'Sem Informações')], default=1, verbose_name='Modelo de Info do Paciente'),
        ),
        migrations.AddField(
            model_name='exame',
            name='modelo_rodape',
            field=models.IntegerField(choices=[(1, 'Completo'), (2, 'Sem Rodapé')], default=1, verbose_name='Modelo do Rodapé'),
        ),
    ]
