# Generated by Django 5.2.7 on 2026-02-23 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_exame_conteudo_apresentacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloreceita',
            options={'ordering': ['nome'], 'verbose_name': 'Modelo de Receita', 'verbose_name_plural': 'Modelos de Receita'},
        ),
        migrations.RemoveField(
            model_name='modeloreceita',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='codigo',
            field=models.CharField(default='000', editable=False, max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='conteudo_apresentacao',
            field=models.TextField(blank=True, help_text='Conteúdo principal da receita', verbose_name='Conteúdo da Receita'),
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='modelo_cabecalho',
            field=models.IntegerField(choices=[(1, 'Logo + Básico'), (2, 'Logo + Completo'), (3, 'Apenas Logo'), (4, 'Sem Cabeçalho')], default=1, verbose_name='Modelo do Cabeçalho'),
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='modelo_info_paciente',
            field=models.IntegerField(choices=[(1, 'Animal + Responsável Resumido'), (2, 'Animal + Responsável Completo'), (3, 'Sem Informações')], default=1, verbose_name='Modelo de Info do Paciente'),
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='modelo_rodape',
            field=models.IntegerField(choices=[(1, 'Completo'), (2, 'Sem Rodapé')], default=1, verbose_name='Modelo do Rodapé'),
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='modelo_titulo',
            field=models.IntegerField(choices=[(1, 'Com Título'), (2, 'Sem Título')], default=1, verbose_name='Modelo do Título'),
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='modeloreceita',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
