# Generated by Django 5.2.7 on 2026-02-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_modeloreceita_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloreceita',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='modeloreceita',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='modeloreceita',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='modeloreceita',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='modeloreceita',
            name='modelo_titulo',
        ),
        migrations.RemoveField(
            model_name='modeloreceita',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='conteudo_encerramento',
            field=models.TextField(blank=True, help_text='Conteúdo da seção de encerramento', verbose_name='Encerramento'),
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='modeloreceita',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modeloreceita',
            name='conteudo_apresentacao',
            field=models.TextField(blank=True, help_text='Conteúdo da seção de apresentação', verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='modeloreceita',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
