# Generated by Django 5.2.7 on 2026-02-23 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def gerar_codigos_sequenciais(apps, schema_editor):
    ModeloReceita = apps.get_model('cadastros', 'ModeloReceita')
    for idx, receita in enumerate(ModeloReceita.objects.order_by('id'), start=1):
        receita.codigo = str(idx).zfill(3)
        receita.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_alter_modeloreceita_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloreceita',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='modeloreceita',
            name='codigo',
            field=models.CharField(default='000', editable=False, max_length=10, verbose_name='Código'),
        ),
        migrations.RunPython(gerar_codigos_sequenciais, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='modeloreceita',
            name='codigo',
            field=models.CharField(default='000', editable=False, max_length=10, unique=True, verbose_name='Código'),
        ),
    ]
