# Generated by Django 5.2.7 on 2026-02-23 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_modeloreceita_autor_modeloreceita_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelodocumento',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='modelodocumento',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='modelodocumento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelodocumento',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='modelodocumento',
            name='codigo',
            field=models.CharField(default='000', editable=False, max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='modelodocumento',
            name='conteudo_apresentacao',
            field=models.TextField(blank=True, help_text='Conteúdo da seção de apresentação', verbose_name='Apresentação'),
        ),
        migrations.AddField(
            model_name='modelodocumento',
            name='conteudo_encerramento',
            field=models.TextField(blank=True, help_text='Conteúdo da seção de encerramento', verbose_name='Encerramento'),
        ),
        migrations.AddField(
            model_name='modelodocumento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='modelodocumento',
            name='modelo_cabecalho',
            field=models.IntegerField(choices=[(1, 'Logo + Básico'), (2, 'Logo + Completo'), (3, 'Apenas Logo'), (4, 'Sem Cabeçalho')], default=1, verbose_name='Modelo do Cabeçalho'),
        ),
        migrations.AddField(
            model_name='modelodocumento',
            name='modelo_info_paciente',
            field=models.IntegerField(choices=[(1, 'Animal + Responsável Resumido'), (2, 'Animal + Responsável Completo'), (3, 'Sem Informações')], default=1, verbose_name='Modelo de Info do Paciente'),
        ),
        migrations.AddField(
            model_name='modelodocumento',
            name='modelo_rodape',
            field=models.IntegerField(choices=[(1, 'Completo'), (2, 'Sem Rodapé')], default=1, verbose_name='Modelo do Rodapé'),
        ),
        migrations.AlterField(
            model_name='modelodocumento',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
