# Generated by Django 5.2.7 on 2026-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_alter_modelodocumento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='Código'),
        ),
    ]
