# Generated by Django 5.2.7 on 2026-02-24 12:04

from django.db import migrations


def populate_exame_codigo(apps, schema_editor):
    """Popula códigos sequenciais para exames existentes"""
    Exame = apps.get_model('cadastros', 'Exame')
    exames = Exame.objects.all().order_by('id')
    
    for idx, exame in enumerate(exames, start=1):
        exame.codigo = str(idx).zfill(3)
        exame.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_exame_codigo'),
    ]

    operations = [
        migrations.RunPython(populate_exame_codigo, migrations.RunPython.noop),
    ]
