# Generated by Django 5.2.7 on 2026-02-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_populate_exame_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='codigo',
            field=models.CharField(default='000', editable=False, max_length=10, unique=True, verbose_name='Código'),
        ),
    ]
