# Generated by Django 5.2.7 on 2026-03-04 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_alter_exame_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filaatendimento',
            name='descricao',
        ),
        migrations.AddField(
            model_name='filaatendimento',
            name='atribuido_a',
            field=models.ForeignKey(blank=True, help_text='Veterinário responsável por atender esta fila', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filas_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a'),
        ),
        migrations.AddField(
            model_name='filaatendimento',
            name='codigo',
            field=models.CharField(default='000', editable=False, max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='filaatendimento',
            name='permanente',
            field=models.BooleanField(default=False, help_text='Se marcado, esta fila aparecerá todos os dias na agenda', verbose_name='Permanente'),
        ),
    ]
