# Generated by Django 5.2.7 on 2026-03-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_remove_filaatendimento_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filaatendimento',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='Código'),
        ),
    ]
