# Generated by Django 6.0.2 on 2026-04-15 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_remove_codigo_default_filaatendimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributoexame',
            options={'ordering': ['exame', 'ordem', 'nome']},
        ),
        migrations.AddField(
            model_name='atributoexame',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='atributoexame',
            name='atributo_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='cadastros.atributoexame', verbose_name='Atributo pai'),
        ),
        migrations.AddField(
            model_name='atributoexame',
            name='largura',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Largura (px)'),
        ),
        migrations.AddField(
            model_name='atributoexame',
            name='obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Obrigatório'),
        ),
        migrations.AddField(
            model_name='atributoexame',
            name='opcoes_preenchimento',
            field=models.TextField(blank=True, null=True, verbose_name='Opções de preenchimento'),
        ),
        migrations.AddField(
            model_name='atributoexame',
            name='ordem',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='atributoexame',
            name='tamanho',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho'),
        ),
        migrations.AddField(
            model_name='atributoexame',
            name='tipo_dado',
            field=models.CharField(blank=True, choices=[('texto', 'Texto'), ('numero', 'Número'), ('selecao', 'Seleção'), ('data', 'Data'), ('booleano', 'Sim/Não')], max_length=20, null=True, verbose_name='Tipo do dado'),
        ),
        migrations.AlterField(
            model_name='atributoexame',
            name='unidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade'),
        ),
    ]
