# Generated by Django 6.0.2 on 2026-04-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_add_atributoexame_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributoexame',
            name='tipo_dado',
            field=models.CharField(blank=True, choices=[('alfanumerico', 'Alfanumérico'), ('data', 'Data'), ('decimal', 'Decimal'), ('texto', 'Texto'), ('inteiro', 'Inteiro')], max_length=20, null=True, verbose_name='Tipo do dado'),
        ),
    ]
