# Generated by Django 6.0.2 on 2026-04-16 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_update_atributoexame_tipo_dado_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenciaexame',
            options={'ordering': ['exame__nome', 'especie__nome', 'nome']},
        ),
        migrations.RemoveField(
            model_name='referenciaexame',
            name='descricao',
        ),
        migrations.AddField(
            model_name='referenciaexame',
            name='especie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referencias_exames', to='cadastros.especie', verbose_name='Espécie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referenciaexame',
            name='idade_final',
            field=models.PositiveIntegerField(default=0, verbose_name='Idade final (meses)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referenciaexame',
            name='idade_inicial',
            field=models.PositiveIntegerField(default=0, verbose_name='Idade inicial (meses)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referenciaexame',
            name='nome',
            field=models.CharField(default='', max_length=150, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemReferenciaExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_inicio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referência início')),
                ('ref_fim', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referência fim')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_referencia', to='cadastros.atributoexame')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastros.referenciaexame')),
            ],
            options={
                'ordering': ['atributo__ordem', 'atributo__nome'],
            },
        ),
    ]
