# Generated by Django 6.0.2 on 2026-04-29 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_redesign_referenciaexame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolovacina',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocolos_vacina', to='cadastros.especie', verbose_name='Espécie'),
        ),
    ]
