# Generated by Django 6.0.2 on 2026-02-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('sales', '0003_sale_forma_pagamento_alter_sale_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('PIX', 'PIX')], max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('venda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='sales.sale')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
