# Generated by Django 5.2.7 on 2026-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_cashregister_financialentry_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
