# Generated by Django 5.2.7 on 2026-03-04 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_atendimento_documento_exame_examearquivo_foto_and_more'),
        ('scheduling', '0004_horariofuncionamento_remove_appointment_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to='scheduling.agendamento'),
        ),
    ]
