# Generated by Django 6.0.2 on 2026-04-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_alter_medicalrecord_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
