# Generated by Django 6.0.2 on 2026-04-09 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_remove_codigo_default_filaatendimento'),
        ('medical_records', '0006_alter_peso_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='patologia',
            name='patologia_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.patologia', verbose_name='Patologia'),
        ),
    ]
