# Generated by Django 6.0.2 on 2026-04-09 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_remove_codigo_default_filaatendimento'),
        ('medical_records', '0007_patologia_patologia_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='conteudo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documento',
            name='modelo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.modelodocumento', verbose_name='Modelo de Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
