# Generated by Django 6.0.2 on 2026-04-09 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_remove_codigo_default_filaatendimento'),
        ('medical_records', '0008_documento_conteudo_documento_modelo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='conteudo',
            field=models.TextField(blank=True, default='', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='modelo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='cadastros.modelodocumento', verbose_name='Modelo de Documento'),
        ),
    ]
