# Generated by Django 6.0.2 on 2026-04-16 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_redesign_referenciaexame'),
        ('medical_records', '0009_alter_documento_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='conclusoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='exame_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_prontuario', to='cadastros.exame'),
        ),
        migrations.AddField(
            model_name='exame',
            name='itens_resultado',
            field=models.TextField(blank=True),
        ),
    ]
