# Generated by Django 6.0.2 on 2026-04-16 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_redesign_referenciaexame'),
        ('medical_records', '0010_add_exame_cadastro_itens_conclusoes'),
        ('patients', '0005_pet_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloVacinaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('interrompida', 'Interrompida')], default='programada', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos_vacina', to='patients.pet')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_pet', to='cadastros.protocolovacina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protocolo de Vacina Registrado',
                'verbose_name_plural': 'Protocolos de Vacinas Registrados',
                'ordering': ['-data_inicial'],
            },
        ),
        migrations.CreateModel(
            name='DoseVacinaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dose', models.PositiveIntegerField()),
                ('data_programada', models.DateField()),
                ('data_aplicacao', models.DateTimeField(blank=True, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=200)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('aplicada', 'Aplicada')], default='programada', max_length=20)),
                ('protocolo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='medical_records.protocolovacinaregistro')),
            ],
            options={
                'verbose_name': 'Dose de Vacina',
                'verbose_name_plural': 'Doses de Vacinas',
                'ordering': ['numero_dose'],
            },
        ),
    ]
