# Generated by Django 6.0.2 on 2026-04-28 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_redesign_referenciaexame'),
        ('medical_records', '0011_protocolovacinaregistro_dosevacinaregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='conteudo',
            field=models.TextField(blank=True, default='', verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='receita',
            name='modelo_receita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_geradas', to='cadastros.modeloreceita', verbose_name='Modelo de Receita'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='prescricao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
