# Generated by Django 6.0.2 on 2026-04-28 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0012_receita_conteudo_receita_modelo_receita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacao',
            name='conteudo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ObservacaoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='observacoes_anexos/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('observacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='medical_records.observacao')),
            ],
        ),
    ]
