# Generated by Django 5.2.7 on 2026-02-10 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['codigo'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='client',
            name='aceita_campanha_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='aceita_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='aceita_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='aceita_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='celular',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='celular_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='como_conheceu',
            field=models.CharField(blank=True, choices=[('rua', 'Passando na rua'), ('facebook', 'Facebook'), ('site', 'Site'), ('instagram', 'Instagram'), ('indicacao', 'Indicação'), ('outros', 'Outros')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='data_aniversario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='inscricao_estadual',
            field=models.CharField(blank=True, choices=[('contribuinte', 'Contribuinte de ICMS'), ('nao_contribuinte', 'Não contribuinte de ICMS'), ('isento', 'Isento de inscrição')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nacionalidade',
            field=models.CharField(blank=True, choices=[('brasileiro', 'Brasileiro'), ('estrangeiro', 'Estrangeiro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='regime_tributario',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('simples', 'Simples')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=500),
        ),
        migrations.AddField(
            model_name='client',
            name='tipo',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nome_completo',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ContatoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('celular', 'Celular'), ('email', 'E-mail'), ('telefone_residencial', 'Telefone Residencial'), ('telefone_comercial', 'Telefone Comercial'), ('outros', 'Outros')], max_length=30)),
                ('valor', models.CharField(max_length=200)),
                ('whatsapp', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_adicionais', to='clients.client')),
            ],
            options={
                'verbose_name': 'Contato Adicional',
                'verbose_name_plural': 'Contatos Adicionais',
            },
        ),
    ]
