# Generated by Django 5.2.7 on 2026-02-10 00:48

from django.db import migrations


def populate_codigo(apps, schema_editor):
    """Popular códigos sequenciais para clientes existentes"""
    Client = apps.get_model('clients', 'Client')
    clients = Client.objects.filter(codigo__isnull=True).order_by('id')
    
    # Encontrar o próximo código disponível
    ultimo = Client.objects.exclude(codigo__isnull=True).order_by('-codigo').first()
    proximo_codigo = (ultimo.codigo + 1) if ultimo else 1
    
    # Atribuir códigos sequenciais
    for client in clients:
        client.codigo = proximo_codigo
        client.save()
        proximo_codigo += 1


def reverse_populate(apps, schema_editor):
    """Reverter a operação (opcional)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_options_remove_client_telefone_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_codigo, reverse_populate),
    ]
