# Generated by Django 5.2.7 on 2026-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_populate_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='obs_celular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='obs_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
