# Generated by Django 6.0.2 on 2026-02-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_vacina_codigo'),
        ('clients', '0007_clear_como_conheceu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='como_conheceu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.origemcliente', verbose_name='Como nos conheceu'),
        ),
    ]
