# Generated by Django 5.2.7 on 2026-02-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_como_conheceu'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
