# Generated by Django 5.2.7 on 2026-02-07 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('celular', models.CharField(blank=True, help_text='Formato: (11) 99999-9999', max_length=15, verbose_name='Celular')),
                ('crmv', models.CharField(blank=True, help_text='Ex: CRMV-SP 12345', max_length=20, verbose_name='CRMV')),
                ('mapa', models.CharField(blank=True, help_text='Ex: MAPA 123456', max_length=20, null=True, verbose_name='Registro MAPA')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de Perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'ordering': ['user__username'],
            },
        ),
    ]
