# Generated by Django 5.2.7 on 2026-02-07 19:32

from django.db import migrations


def fill_empty_cpf(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    import random
    
    # Preencher CPFs vazios com valores temporários únicos
    profiles_without_cpf = UserProfile.objects.filter(cpf__isnull=True) | UserProfile.objects.filter(cpf='')
    
    for idx, profile in enumerate(profiles_without_cpf, start=1):
        # Gerar CPF temporário único baseado no ID
        temp_cpf = f'000.000.00{idx:01d}-{random.randint(10,99)}'
        profile.cpf = temp_cpf
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RunPython(fill_empty_cpf, reverse_code=migrations.RunPython.noop),
    ]
