# Generated by Django 5.2.7 on 2026-02-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fill_empty_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(default='00000000000', help_text='Formato: 000.000.000-00', max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
