# Generated by Django 5.2.7 on 2026-03-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_make_cpf_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='perfil',
            field=models.CharField(blank=True, choices=[('veterinario', 'Veterinário'), ('veterinario_plantonista', 'Veterinário Plantonista'), ('veterinario_especialista', 'Veterinário Especialista'), ('consultor', 'Consultor'), ('administrador', 'Administrador'), ('recepcionista', 'Recepcionista')], default='recepcionista', max_length=50, verbose_name='Perfil do Usuário'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
    ]
