# Generated by Django 6.0.2 on 2026-05-06 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_id_alter_stockmovement_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['nome'], 'verbose_name': 'Produto/Serviço', 'verbose_name_plural': 'Produtos/Serviços'},
        ),
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='estoque_maximo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='pendencia_fiscal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tipo',
            field=models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço')], default='produto', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='inventory.brand'),
        ),
    ]
