# Generated by Django 6.0.2 on 2026-02-04 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('CAO', 'Cão'), ('GATO', 'Gato'), ('OUTRO', 'Outro')], max_length=10)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('idade_estimada', models.PositiveIntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porte', models.CharField(blank=True, max_length=50, null=True)),
                ('cor_pelagem', models.CharField(blank=True, max_length=100, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('microchip', models.CharField(blank=True, max_length=50, null=True)),
                ('temperamento', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clients.client')),
            ],
        ),
    ]
