# Generated by Django 5.2.7 on 2026-02-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='cor_pelagem',
        ),
        migrations.AddField(
            model_name='pet',
            name='pelagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.pelagem'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.especie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.raca'),
        ),
    ]
