# Generated by Django 6.0.2 on 2026-02-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_pet_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['codigo'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AddField(
            model_name='pet',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='esterilizacao',
            field=models.CharField(blank=True, choices=[('fertil', 'Fértil'), ('castrado', 'Castrado'), ('vasectomizado', 'Vasectomizado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='marcacoes',
            field=models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=500),
        ),
        migrations.AddField(
            model_name='pet',
            name='numero_pedigree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='pedigree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('I', 'Indeterminado')], max_length=1),
        ),
    ]
