# Generated by Django 5.2.7 on 2026-02-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_pet_options_pet_codigo_pet_esterilizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('vivo', 'Vivo'), ('obito', 'Óbito')], default='vivo', max_length=10),
        ),
    ]
