# Generated by Django 6.0.2 on 2026-02-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_service_alter_saleitem_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('PIX', 'PIX')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=10),
        ),
    ]
